1240 preparing to get started
bitfoundation/bitframework pull request #1253
Opened 2021-12-30 13:17 UTC by sajadkardel

additional work on this branch contains is :

- add AutoMapper 

- add fluent API Entity Configurations

- using IdentityDbContext instead of DbContext. this is for implementing User and Role Entity by Default

- create role controller with sample CRUD

- implement generic repository for all the entities

2022-01-04 08:49 UTC, ysmoradi requested changes

2022-01-04 08:49 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/TodoTemplate/Api/Controllers/RoleController.cs
> +            return Get(cancellationToken).FirstOrDefault(role => role.Id == id);
Use FirstOrDefaultAsync @sajadkardel

2022-01-04 08:49 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/TodoTemplate/Api/Controllers/RoleController.cs
> +            _context.Add(roleToAdd);
Use AddAsync & SaveChangesAsync @sajadkardel

2022-01-04 08:49 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/TodoTemplate/Web/Services/Extensions/ServiceCollectionExtensions.cs
> +                HttpClient httpClient = new(sp.GetRequiredService<TodoTemplateHttpClientHandler>()) { BaseAddress = new Uri("https://localhost:5001/api/") };
We've IConfiguration & appsettings in both app & web projects. Please use ApiServerAddress instead of hard coded server URL @sajadkardel

2022-01-04 17:03 UTC, ysmoradi approved these changes

2022-01-05 15:54 UTC, msynk requested changes

2022-01-06 06:56 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/TodoTemplate/Api/Controllers/RoleController.cs
> +            var roleToDelete = await _context.Roles.FirstOrDefaultAsync(role => role.Id == id, cancellationToken);
I think so @msynk

2022-01-06 06:57 UTC, ysmoradi commented
I'm gonna do whatever you've requested on my own. I've to merge this PR.

2022-01-06 06:57 UTC, merged