Add breadcrumb (#1188)
bitfoundation/bitframework pull request #1469
Opened 2022-02-17 15:55 UTC by rbasereh

this closed.

2022-02-17 15:57 UTC, rbasereh commented
Add breadcrumb (#1188) #1469
Breadcrumbs used as a navigational aid

2022-02-21 20:59 UTC, msynk requested changes

2022-02-21 20:59 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.Fluent.scss
> +.bit-brc-fluent li{
plz fix the code formatting issue

2022-02-21 20:59 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/BreadcrumbItem.cs
> +        /// <summary>
plz add a newline before this line

2022-02-21 20:59 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor.cs
> +        [Parameter] public string OnRenderOverflowIcon { get; set; } = "bit-icon--More";
plz add an empty line before this line

2022-02-21 20:59 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor.cs
> +
plz remove these empty lines

2022-02-21 20:59 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/BreadcrumbItem.cs
> +namespace Bit.Client.Web.BlazorUI
plz add an empty line before this line

2022-02-21 21:04 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor
> +<div @ref="RootElement"
plz add an empty line before this line

2022-02-21 21:13 UTC, msynk requested changes

2022-02-21 21:13 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor.cs
> +        /// <summary>
plz add a newline before this line

2022-02-21 21:13 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor.cs
> +        /// <summary>
plz add a newline before this line

2022-02-21 21:13 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Breadcrumb/Breadcrumb.razor.cs
> +        /// <summary>
plz add a newline before this line

2022-02-21 21:16 UTC, msynk approved these changes

2022-02-21 21:31 UTC, merged