Add documentation to BitPersona #1475
bitfoundation/bitframework pull request #1503
Opened 2022-02-22 15:57 UTC by zoha-shobbar

this closes #1475

2022-02-22 16:32 UTC, msynk requested changes
please convert these simple comments to summary documentation comments.

2022-02-23 07:37 UTC, msynk requested changes

2022-02-23 07:37 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Persona/BitPersona.razor.cs
>          [Parameter] public string? PresenceIcon { get; set; }
plz add a documentation comment for this parameter

2022-02-23 13:22 UTC, msynk approved these changes

2022-02-23 13:28 UTC, maryamhdr approved these changes

2022-02-23 13:31 UTC, merged