fix not found photo error on edit profile page (#1435 )
bitfoundation/bitframework pull request #1560
Opened 2022-02-28 14:54 UTC by sajadkardel

this closes #1435

2022-02-28 15:51 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/TodoTemplate.Api.csproj
> +    <ItemGroup>
Please remove this

2022-02-28 15:51 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Shared/Dtos/Account/UserDto.cs
> +    public Guid? ProfileImageName { get; set; }
ProfileImageName could be string instead of Guid

2022-02-28 15:51 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Shared/TodoTemplate.Shared.csproj
> +    <ItemGroup>
Please remove this

2022-02-28 15:52 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/EditProfile.razor.cs
> +        IsLoadingPage = true;
Use try-finally approach

2022-02-28 15:53 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/EditProfile.razor.cs
> +        IsLoadingSaveButton = true;
Use try finally approach

2022-03-01 17:49 UTC, ysmoradi submitted a review, later dismissed

2022-03-02 05:49 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Shared/Resources/ErrorStrings.resx
> +    <value>User's Image could not be found</value>
The `Image` should be written in lower case as `image`.

2022-03-02 07:35 UTC, maryamhdr approved these changes

2022-03-02 09:21 UTC, msynk requested changes
plz resolve the issues we talked about

2022-03-02 10:38 UTC, maryamhdr submitted a review, later dismissed

2022-03-02 11:40 UTC, msynk requested changes

2022-03-02 11:40 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AttachmentController.cs
> +            throw new BadRequestException();
plz just re-throw the exception here. do not introduce a new exception.
i meant use `throw;`

2022-03-02 11:40 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AttachmentController.cs
> +            throw new BadRequestException();
plz just re-throw the exception here too.

2022-03-02 11:42 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AttachmentController.cs
> +                var filePath = Directory.GetFiles(_appSettings.UserProfileImagePath,
filePath == path
am I wrong?

2022-03-02 12:21 UTC, msynk approved these changes

2022-03-02 12:21 UTC, merged