Change Program.cs of Playground.Web to use WebApplication
bitfoundation/bitframework pull request #1583
Opened 2022-03-05 19:56 UTC by RezaKargar

This resolves #1579 by changing Program.cs of Playground.Web to use `WebApplication` rather than `HostBuilder`

2022-03-05 20:02 UTC, RezaKargar commented
@ysmoradi Please check this out

2022-03-05 20:09 UTC, ysmoradi commented
@RezaKargar 
The structure has 3 files
[Program.cs](https://github.com/bitfoundation/bitframework/blob/develop/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Program.cs)
[Middlewares.cs](https://github.com/bitfoundation/bitframework/blob/develop/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Startup/Middlewares.cs)
[Services.cs](https://github.com/bitfoundation/bitframework/blob/develop/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Startup/Services.cs)
But you're submitting only 1 file.
The Todo template's web project is following Todo template's API project structure which has the same 3 files.

2022-03-05 20:29 UTC, RezaKargar commented
@ysmoradi 
Oh, right!
I'll fix it

2022-03-06 21:02 UTC, ysmoradi commented
This sounds good to me
Based on the discussion that we did, I ask you to handle this PR @msynk

2022-03-13 11:04 UTC, ysmoradi commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Program.cs
>  #if BlazorWebAssembly || BlazorServer
Could you please use one Main method to be the same as TodoTemplate's web project?
Also add UseUrls

https://github.com/bitfoundation/bitframework/blob/develop/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Program.cs#L12-L20

https://github.com/bitfoundation/bitframework/blob/develop/src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Program.cs#L40-L42

@RezaKargar

2022-03-13 11:04 UTC, ysmoradi requested changes
Please review and fix provided comments

2022-03-13 17:16 UTC, ysmoradi approved these changes

2022-03-13 17:17 UTC, msynk approved these changes

2022-03-13 17:18 UTC, merged