Modify BitCarousel component styles (#1584)
bitfoundation/bitframework pull request #1602
Opened 2022-03-07 10:12 UTC by saeedhalab

This closes #1584

2022-03-07 10:22 UTC, maryamhdr requested changes

2022-03-07 10:22 UTC, maryamhdr commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Carousel/BitCarousel.Fluent.scss
> +            background-color: #001dff;
plz use a color variable declared in _colors.fluent.scss

2022-03-07 10:22 UTC, maryamhdr commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Carousel/BitCarousel.Fluent.scss
> +        padding: 4px 0;
plz convert all the values provided in px to rem

2022-03-07 10:22 UTC, maryamhdr commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Carousel/BitCarousel.Fluent.scss
>          color: white;
use the $White variable instead

2022-03-07 10:22 UTC, maryamhdr commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Carousel/BitCarousel.Fluent.scss
> +        background-color: #484644;
plz use a color variable declared in _colors.fluent.scss

2022-03-08 10:45 UTC, maryamhdr approved these changes

2022-03-08 11:06 UTC, msynk approved these changes

2022-03-08 11:07 UTC, merged