Incorrect 'IsEnabled' handling in BitRadioButtonGroup and BitRadioButtonOption component (#1369)
bitfoundation/bitframework pull request #1724
Opened 2022-03-17 11:54 UTC by sajadkardel

this closes #1369

2022-03-27 15:19 UTC, msynk requested changes

2022-03-27 15:19 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/RadioButtonGroup/BitRadioButtonOption.razor
> +               required="@(RadioButtonGroup != null ? RadioButtonGroup.IsRequired : false)"
plz change this line to this:
```cs
RadioButtonGroup?.IsRequired ?? false
```

2022-03-27 15:19 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/RadioButtonGroup/BitRadioButtonOption.razor.cs
> +                var isEnabled = IsEnabled is false || (RadioButtonGroup is not null && RadioButtonGroup.IsEnabled is false);
rename this variable to `isDisabled`

2022-03-28 04:20 UTC, msynk approved these changes

2022-03-28 09:29 UTC, maryamhdr approved these changes

2022-03-28 09:31 UTC, merged