Enable source map generation for ts/js files (#1711)
bitfoundation/bitframework pull request #1730
Opened 2022-03-18 15:21 UTC by RezaKargar

This closes #1711

2022-03-18 15:25 UTC, RezaKargar commented
@ysmoradi Please checkout this PR

2022-03-20 10:16 UTC, msynk requested changes
the minification is done by the WebCompiler, I don't think that enabling the sourcemap option in tsconfig file has any effect on this issue.
@ysmoradi any idea?

2022-03-20 10:16 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/wwwroot/scripts/todoTemplate.ts
> +        return "";
plz revert this change

2022-03-20 10:59 UTC, ysmoradi commented
> the minification is done by the WebCompiler, I don't think that enabling the sourcemap option in tsconfig file has any effect on this issue. @ysmoradi any idea?

This won't solve the issue. We need to do something beyond typescript settings

2022-03-24 09:16 UTC, msynk commented
since this is not the solution, I'm closing this PR.

2022-03-24 09:16 UTC, closed without merging