Implement validation for BitRating component
bitfoundation/bitframework pull request #1741
Opened 2022-03-20 09:06 UTC by RezaKargar

This closes #1532

2022-03-20 09:10 UTC, RezaKargar commented
@Cyrus-Sushiant Please take a look at my changes

2022-03-20 10:38 UTC, msynk requested changes

2022-03-20 10:38 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Rating/BitRating.Fluent.scss
> +            color: $Red20 !important;
plz do NOT use `!important` at all.

2022-03-20 10:38 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Rating/BitRating.razor.cs
> +        /// Only provide this if the CurrentValue is an uncontrolled component; otherwise, use the rating property.
plz change the `rating` to `Value` in the last sentence.

2022-03-20 10:38 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Rating/BitRatingDemo.razor.cs
> +        public class FormModel
plz move this class into a separate file

2022-03-24 20:22 UTC, Cyrus-Sushiant requested changes

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Rating/BitRating.razor.cs
> +using System.Diagnostics.CodeAnalysis;
Remove `RatingHasBeenSet` field

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Rating/BitRating.razor.cs
> +                CurrentValue = (double)DefaultValue;
Use the HasValue property instead of cast

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Rating/BitRating.razor.cs
> +        private void HandleOnCurrentValueChanged(object? sender, EventArgs args) => ClassBuilder.Reset();
Plz unregister event handler on Dispose, like BitSearchBox.

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Rating/BitRatingDemo.razor
> +    <ComponentExampleBox Title="BitRating with validation" HTMLSourceCode="@example3HTMLCode" CSharpSourceCode="@example3CSharpCode" ExampleId="example2">
Plz change ExampleId to example3

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Rating/BitRatingDemo.razor.cs
>                  Description = "Default rating. Must be a number between min and max. Only provide this if the Rating is an uncontrolled component; otherwise, use the rating property.",
Rename `Rating` to `Value` in line 101 and `RatingChanged` to `ValueChanged` in line 108

2022-03-24 20:22 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Rating/BitRatingDemo.razor.cs
> +        private readonly string example3HTMLCode = @"<div>
Plz, remove the div tag from the start sample code.

2022-03-25 15:37 UTC, Cyrus-Sushiant approved these changes

2022-03-26 09:05 UTC, msynk approved these changes

2022-03-26 09:06 UTC, merged