add new bit choice group component (#1401 )
bitfoundation/bitframework pull request #1823
Opened 2022-04-01 05:04 UTC by sajadkardel

this closes #1401

2022-04-03 20:14 UTC, Cyrus-Sushiant requested changes

2022-04-03 20:14 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/ChoiceGroup/BitChoiceGroupDemo.razor.cs
> +            },
Add `Value` and `ValueChanged` to the list of parameter

2022-04-03 20:14 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Inputs/BitChoiceGroupTests.cs
> +            }
I think it is better to check that it doesn't have class `disabled` when the above condition is false.
```csharp
else 
{
  Assert.IsFalse(bitChoiceGroupOptions.ClassList.Contains($"bit-chgo-disabled-{visualClass}"));
}
```

2022-04-04 20:56 UTC, Cyrus-Sushiant requested changes

2022-04-04 20:56 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/ChoiceGroup/BitChoiceGroup.razor.cs
> +        [Parameter] public string? DefaultSelectedKey { get; set; }
Plz, change `DefaultSelectedKey` to `DefaultValue`

2022-04-04 20:56 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/ChoiceGroup/BitChoiceGroupOption.cs
> +    public class BitChoiceGroupOption
Plz add `AriaLabel`, `LabelId` and `Id` prop like [fluent](https://developer.microsoft.com/en-us/fluentui#/controls/web/choicegroup)

2022-04-06 12:09 UTC, msynk commented
@Cyrus-Sushiant plz re-review

2022-04-07 12:47 UTC, Cyrus-Sushiant approved these changes

2022-04-07 15:00 UTC, msynk approved these changes

2022-04-07 15:03 UTC, merged