using validation of the bit input components in the todo template forms (#1792 )
bitfoundation/bitframework pull request #1829
Opened 2022-04-04 02:18 UTC by sajadkardel

this closes #1792

2022-04-04 10:12 UTC, maryamhdr requested changes

2022-04-04 10:12 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Models/ResetPasswordModel.cs
> +        [Compare(nameof(NewPassword), ErrorMessage = "Password confirmation doesn't match Password.")]
The `ErrorMessage` should be "Password confirmation doesn't match the new password." :)

2022-04-04 10:35 UTC, maryamhdr approved these changes

2022-04-04 12:49 UTC, msynk requested changes

2022-04-04 12:49 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/ForgotPassword.razor.cs
> +    private async Task DoForgotPassword()
plz rename this method back to submit. the `DoForgotPassword` is not an appropriate name here.

2022-04-04 12:49 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/ResetPassword.razor.cs
> +    private async Task DoResetPassword()
again, plz rename this method back to Submit.

2022-04-04 15:13 UTC, msynk submitted a review, later dismissed

2022-04-04 15:17 UTC, maryamhdr submitted a review, later dismissed

2022-04-04 15:40 UTC, Cyrus-Sushiant requested changes

2022-04-05 09:46 UTC, maryamhdr approved these changes

2022-04-05 10:35 UTC, Cyrus-Sushiant approved these changes

2022-04-05 11:52 UTC, merged