Enhance the README file of the BitBswup project (#1449)
bitfoundation/bitframework pull request #1835
Opened 2022-04-04 20:02 UTC by Cyrus-Sushiant

This closes #1449

2022-04-05 07:56 UTC, ysmoradi requested changes

2022-04-05 07:56 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Bswup/README.md
> +public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
Please remove Configure method. app.UseStaticFiles is enough. They might be using new .net 6 style project which uses web app builder

2022-04-05 07:57 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Bswup/README.md
> +- scope: The scope of the service worker determines which files the service worker controls.
Provide a link to scope in service worker docs

2022-04-05 07:57 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Bswup/README.md
> +-sw: The sw is name and path service worker file.
space is missing before sw

2022-04-05 07:58 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Bswup/README.md
> +            reloadButton.style.display = 'block';
what's reloadButton here?

2022-04-05 18:51 UTC, ysmoradi requested changes

2022-04-05 18:51 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Bswup/README.md
> +5. In the default document (`index.html` or `_Host.cshtml`), add the `Bit.Tooling.Bswup` reference after the <script> tag for the Blazor script.
_Host.cshtml, index.html or _Layout.cshtml
This is also wrong in bit component getting started where we add style & script as described in getting started. @maryamhdr

2022-04-06 14:59 UTC, msynk commented
@Cyrus-Sushiant any updates?

2022-04-06 19:38 UTC, msynk approved these changes

2022-04-06 19:39 UTC, msynk approved these changes

2022-04-06 19:40 UTC, merged