add tests for bit choice group component (#1837)
bitfoundation/bitframework pull request #1849
Opened 2022-04-07 15:44 UTC by sajadkardel

this closes #1837

2022-04-08 17:50 UTC, msynk commented
@Cyrus-Sushiant plz review

2022-04-08 19:02 UTC, Cyrus-Sushiant requested changes

2022-04-09 20:02 UTC, msynk commented
@sajadkardel any updates?

2022-04-10 16:08 UTC, maryamhdr approved these changes

2022-04-11 08:26 UTC, msynk commented
@Cyrus-Sushiant plz re-review

2022-04-11 14:34 UTC, Cyrus-Sushiant approved these changes

2022-04-11 14:54 UTC, msynk approved these changes

2022-04-11 14:54 UTC, merged