Modify some styles of the BitPersona component (#1841)
bitfoundation/bitframework pull request #1858
Opened 2022-04-10 11:50 UTC by saeedhalab

This closes #1841

2022-04-10 13:35 UTC, msynk requested changes

2022-04-10 13:35 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Styles/Fluent/colors.fluent.scss
> +$magenta: #b4009e;
use Pascal casing for the color naming.
please rename this color to `Magneta`.

2022-04-10 13:35 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Styles/Fluent/colors.fluent.scss
> +$orange10: #ffaa44;
please rename this color to `Orange10`.

2022-04-10 13:35 UTC, msynk commented
@maryamhdr plz submit your suggestion for the color names.

2022-04-10 16:00 UTC, maryamhdr approved these changes

2022-04-10 16:01 UTC, maryamhdr commented
> @maryamhdr plz submit your suggestions for the color names.

We had discussed the names before with @saeedhalab.

2022-04-11 08:27 UTC, msynk approved these changes

2022-04-11 08:28 UTC, merged