Use Dto class insted of ViewModel class (#1855)
bitfoundation/bitframework pull request #1863
Opened 2022-04-11 20:29 UTC by Cyrus-Sushiant

This closes #1855

2022-04-12 10:18 UTC, msynk requested changes

2022-04-12 10:18 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/ResetPassword.razor.cs
> +            ResetPasswordModel.Token = Email;
Token = Email ?

2022-04-12 10:18 UTC, msynk commented
@maryamhdr & @ysmoradi plz review

2022-04-13 07:11 UTC, msynk approved these changes

2022-04-13 10:16 UTC, maryamhdr approved these changes

2022-04-13 11:21 UTC, merged