Add a condition to throw an error (#1866)
bitfoundation/bitframework pull request #1867
Opened 2022-04-13 10:04 UTC by mohabbati

This closes #1866

2022-04-13 10:09 UTC, maryamhdr approved these changes

2022-04-13 11:19 UTC, msynk commented
this PR needs a rewrite based on a conversation between me @mohabbati

2022-04-15 07:18 UTC, msynk commented
@mohabbati any news or updates?

2022-04-17 04:37 UTC, maryamhdr requested changes

2022-04-17 04:37 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Shared/Resources/ErrorStrings.resx
> +    <value>Your email already confirmed.</value>
The value of this message is better to be like this:
`Your email is already confirmed.`

2022-04-17 04:37 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUpConfirmation.razor
> +        }
it's better to add a blank line after `@if {...}`

2022-04-17 04:37 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUpConfirmation.razor
> +
This blank line is redundant

2022-04-17 12:42 UTC, msynk requested changes

2022-04-17 12:43 UTC, msynk commented
@mohabbati plz update this PR based on our last conversation :)

2022-04-18 10:36 UTC, msynk commented
@mohabbati plz resolve the conflict in the `SignUp.razor` file

2022-04-18 10:36 UTC, msynk commented
@maryamhdr plz review this PR

2022-04-18 10:46 UTC, msynk requested changes

2022-04-18 10:46 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/compilerconfig.json
> +  }
plz correct the formatting in this file based on the configurations of the `.editorcofig` file. (tab-size & indenting-size equals to 4 spaces)

2022-04-18 10:46 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
> +            SignUpMessage = ErrorStrings.ResourceManager.Translate(e.Message, SignUpModel.Email!);
plz don't use `!` to bypass nullability checks, instead check at the start of the method that this property (`SignUpModel.Email`) is not null (or if it is null, simply return).

2022-04-18 10:46 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor
> +        @if (IsSignedUp is false)
plz revert this if statement. it's better to check for the `true` value if there is an else block.

2022-04-18 10:58 UTC, Cyrus-Sushiant requested changes

2022-04-18 10:58 UTC, Cyrus-Sushiant commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AuthController.cs
>          if (!result.Succeeded)
Plz, use `is false` instead of `!`

2022-04-19 11:16 UTC, msynk requested changes

2022-04-19 11:16 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor
> +                OnClick="WrapHandled(ResendLink)">
code formatting issue

2022-04-19 11:16 UTC, msynk commented
@maryamhdr & @Cyrus-Sushiant 
plz re-review this PR

2022-04-20 05:49 UTC, msynk submitted a review, later dismissed

2022-04-20 05:50 UTC, msynk commented
There are still some code formatting issues remains that I leave to the other reviewers 😁
@maryamhdr & @Cyrus-Sushiant

2022-04-20 08:45 UTC, maryamhdr requested changes

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AuthController.cs
No blank line is needed here

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/Controllers/AuthController.cs
> +            throw new BadRequestException(nameof(ErrorStrings.EmailAlreadyConfirmed));
I think it's better to wrap the statement of the `if` condition between `{...}`

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
The blank line is not needed here

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
The blank line is not needed here

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
> +
The blank line is not needed here

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
> +
The blank line is not needed here

2022-04-20 08:45 UTC, maryamhdr commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/SignUp.razor.cs
> +
The blank line is not needed here

2022-04-20 17:28 UTC, Cyrus-Sushiant approved these changes

2022-04-20 18:55 UTC, maryamhdr approved these changes

2022-04-20 21:16 UTC, Cyrus-Sushiant approved these changes

2022-04-21 08:56 UTC, msynk approved these changes

2022-04-21 08:57 UTC, merged