Add BitPersona demo page (#1814)
bitfoundation/bitframework pull request #1869
Opened 2022-04-13 18:26 UTC by saeedhalab

This closes #1814

2022-04-13 20:12 UTC, msynk requested changes

2022-04-13 20:12 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.scss
> +    margin:20px 0 ;
plz use `rem`

2022-04-13 20:12 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/compilerconfig.json
> +  }
so you are another `code formatting` destroyer 😁
plz use the correct indenting (4 spaces not 2 spaces)

2022-04-13 20:12 UTC, msynk commented
@maryamhdr 
@Cyrus-Sushiant 
please review this PR

2022-04-14 07:01 UTC, msynk submitted a review, later dismissed

2022-04-14 07:05 UTC, Cyrus-Sushiant requested changes

2022-04-14 07:05 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +            LinkType=LinkType.Link,
Plz, add space before and after `=`

2022-04-14 07:05 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +
Plz, Remove blank line

2022-04-14 07:05 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +<style>
I think, we don't need style in the example.

2022-04-14 11:29 UTC, maryamhdr submitted a review, later dismissed

2022-04-14 11:29 UTC, maryamhdr commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +            DefaultValue = " -1",
Remove the redundant space

2022-04-14 11:29 UTC, maryamhdr commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +            Href="#precence-status",
add a space before and after the `=`

2022-04-15 07:14 UTC, msynk commented
@maryamhdr & @Cyrus-Sushiant plz re-review 😁

2022-04-15 07:15 UTC, msynk commented
@saeedhalab plz resolve the comments that you believe are resolved after pushing new changes.

2022-04-15 10:18 UTC, Cyrus-Sushiant requested changes

2022-04-15 10:18 UTC, Cyrus-Sushiant commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/Persona/BitPersonaDemo.razor.cs
> +                    Description = "",
Plz, Remove `Description` when set empty

2022-04-17 12:27 UTC, msynk commented
@Cyrus-Sushiant plz re-review

2022-04-17 12:48 UTC, Cyrus-Sushiant approved these changes

2022-04-17 14:10 UTC, msynk approved these changes

2022-04-17 14:11 UTC, merged