Handled the bug (#1887)
bitfoundation/bitframework pull request #1888
Opened 2022-04-17 08:17 UTC by mohabbati

This closes #1887

2022-04-17 12:30 UTC, msynk commented
@ysmoradi & @maryamhdr & @Cyrus-Sushiant plz review this PR

2022-04-17 12:35 UTC, msynk requested changes

2022-04-17 12:35 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/ResetPassword.razor.cs
> +    public TodoTemplateAuthenticationStateProvider TodoTemplateAuthenticationStateProvider { get; set; } = default!;
plz put the attribute in the same line as the property

2022-04-17 12:35 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/ResetPassword.razor.cs
> +                NavigationManager.NavigateTo("/");
plz use `{` and `}` here

2022-04-18 11:20 UTC, ysmoradi commented
We're using the same approach in sign in & up pages
@msynk

2022-04-18 13:36 UTC, maryamhdr approved these changes

2022-04-18 14:50 UTC, msynk approved these changes

2022-04-18 14:51 UTC, merged