Implement the `NotFoundPage` for the `TodoTemplate` project (#1767)
bitfoundation/bitframework pull request #1920
Opened 2022-04-25 12:47 UTC by sajadkardel

this closes #1767

2022-04-25 13:22 UTC, maryamhdr approved these changes

2022-04-25 14:54 UTC, maryamhdr approved these changes

2022-04-26 06:33 UTC, msynk requested changes

2022-04-26 10:20 UTC, sajadkardel commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Components/NotFoundPage.razor
> +    <div class="error-description">Ooops, Something went wrong.</div>
This message was written in Design
But yes, I agree that this is not a good message. I will change it.

2022-04-26 10:26 UTC, sajadkardel commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Components/NotFoundPage.razor
> +<div class="page-container">
We have considered the first-class on all pages as `page-container`.
Especially on this page do we want this name to change? @msynk

2022-04-26 10:31 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Components/NotFoundPage.razor
> +<div class="page-container">
this is not a page, that's why I suggested changing it to `main`, and since the style is isolated it's a proper name.

2022-04-26 10:37 UTC, msynk requested changes

2022-04-26 10:37 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Components/TodoTemplateNotFound.razor
> +<div class="main-container">
not `main-container`, just `main`

2022-04-26 10:43 UTC, msynk approved these changes

2022-04-26 10:47 UTC, msynk requested changes
bring back the compilerconfig required changes. just remove the indenting

2022-04-26 11:37 UTC, maryamhdr approved these changes

2022-04-26 11:38 UTC, msynk approved these changes

2022-04-26 11:39 UTC, merged