Revise the parameters of the Bit components in the TodoTemplate proje…
bitfoundation/bitframework pull request #1939
Opened 2022-04-28 12:07 UTC by MohammadJavadTabari

I just found one file that needs to modify, 'EditProfile.razor' on the 'BitRadioButtonOption' parameter 'key'. I checked out other components and pages in 'ToDoTemplate.Web' all parameters are correct. let me know if there is more.
this closes #1931

2022-04-28 21:02 UTC, Cyrus-Sushiant requested changes

2022-04-28 21:02 UTC, Cyrus-Sushiant commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/EditProfile.razor
>                  <BitRadioButtonGroup @bind-SelectedKey="UserToEdit.GenderAsString"
Plz, use `@bind-Value` instead of `@bind-SelectedKey`

2022-04-29 05:02 UTC, msynk commented
you should not put anything other than the `this closes ...` in the description of the PR. if you need to add some info to your PR plz use the comment.

2022-04-29 05:03 UTC, msynk commented
@Cyrus-Sushiant 
are we sure that there aren't any more required updates?

2022-04-29 05:03 UTC, msynk commented
@MohammadJavadTabari 
plz resolve the conflict

2022-04-29 08:37 UTC, Cyrus-Sushiant commented
> @Cyrus-Sushiant are we sure that there aren't any more required updates?

No. The `DefaultIsChecked` parameter of BitCheckbox in `Todo.razor` page must be changed

2022-04-30 09:28 UTC, MohammadJavadTabari commented
@msynk 
@Cyrus-Sushiant 
thank's for your comments, I will fix it now

2022-04-30 10:51 UTC, MohammadJavadTabari commented
@msynk
@Cyrus-Sushiant 
what mentioned above is done, and I keep searching for more problems like that.
plz, tell me if you see more unsolved problems related to this issue.

2022-04-30 14:31 UTC, Cyrus-Sushiant commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/EditProfile.razor
>                  <BitRadioButtonGroup @bind-SelectedKey="UserToEdit.GenderAsString"
Please fix the above issue. @MohammadJavadTabari

2022-04-30 17:10 UTC, maryamhdr approved these changes

2022-04-30 20:53 UTC, Cyrus-Sushiant approved these changes

2022-05-01 04:02 UTC, msynk approved these changes

2022-05-01 04:03 UTC, merged