support submitting the form by pressing Enter key on the Edit Profile page in the `TodoTemplate` (#1936)
bitfoundation/bitframework pull request #1958
Opened 2022-05-01 13:34 UTC by saeedhalab

This closes #1936

2022-05-02 05:04 UTC, msynk requested changes

2022-05-02 05:04 UTC, msynk commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/EditProfile.razor.cs
> +            IsSaveButtonEnabled = false;
why this change?
i think it has a bad effect on the UX of this form

2022-05-02 05:41 UTC, msynk commented
@maryamhdr & @Cyrus-Sushiant 
plz review this PR

2022-05-03 18:51 UTC, Cyrus-Sushiant approved these changes

2022-05-05 06:32 UTC, msynk approved these changes

2022-05-05 06:33 UTC, merged