Style issues of the `BitDatePicker` in small screen (#1757)
bitfoundation/bitframework pull request #1979
Opened 2022-05-09 03:40 UTC by sajadkardel

this closes #1757

2022-05-09 12:50 UTC, maryamhdr approved these changes

2022-05-09 13:24 UTC, msynk requested changes

2022-05-10 05:23 UTC, msynk commented
@Cyrus-Sushiant plz review

2022-05-10 07:25 UTC, Cyrus-Sushiant approved these changes

2022-05-10 12:03 UTC, msynk approved these changes

2022-05-10 12:03 UTC, merged