Add login form in swagger UI
bitfoundation/bitframework pull request #1997
Opened 2022-05-11 13:46 UTC by milad-karimifard

2022-05-11 19:26 UTC, ysmoradi requested changes
I think we've lost the chance to provide a sample to our audience to show how they can call the api provided by todo template using javascript.
I'd prefer using async/await + fetch. I also recommend using const/let instead of var.
This code need heavy refactor to make sure it uses modern javascript
I also prefer another name other than customer-swagger-login.js, something more general is better in my opinion. For example swagger-utils.js What do you think @msynk @milad-karimifard

2022-05-11 22:51 UTC, msynk commented
@milad-karimifard 
first of all, thanks a lot for your contribution. I appreciate it a lot. 👍
the code you've provided seems to be borrowed from somewhere like this article:
https://www.codedesigntips.com/2021/06/28/swagger-ui-with-login-form-and-role-based-api-visibility/
so if it's borrowed plz provide the source in the code.
and also the javascript code needs to be converted to typescript first before getting reviewed.

2022-05-13 13:05 UTC, msynk commented
IMO, it seems fine now.
@ysmoradi could you plz review this PR and also test the script on your machine?

2022-05-13 13:05 UTC, msynk approved these changes

2022-05-13 13:19 UTC, ysmoradi requested changes

2022-05-13 13:21 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/wwwroot/swagger/swagger-utils.js
> +        let userName = userNameInput.value;
Use const instead of let when possible

2022-05-13 13:21 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Api/wwwroot/swagger/swagger-utils.js
> +    const result = caller(args);
use `async await`
```js
const result = await caller(args);
reloadPage(swagger);
```

2022-05-13 15:03 UTC, ysmoradi approved these changes

2022-05-13 15:04 UTC, ysmoradi commented
I'm gonna merge this PR right after testing that on my local machine @milad-karimifard @msynk 
Thanks!

2022-05-14 06:46 UTC, merged