Rename ``TodoTemplate.Infra`` project to ``TodoTemplate.Iac`` in ``TodoTemplate`` solution
bitfoundation/bitframework pull request #2045
Opened 2022-05-17 12:38 UTC by msangtarash

this closes #1948

2022-05-17 14:56 UTC, ysmoradi requested changes

2022-05-17 14:56 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/_Layout.cshtml
> -@using TodoTemplate.Shared.Infra;
Please revert this change

2022-05-17 14:56 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.Templates/TodoTemplate/Web/Pages/_Host.cshtml
> -@using TodoTemplate.Shared.Infra;
Please revert this change

2022-05-17 18:39 UTC, msynk requested changes
please revert all changes to the `TodoTemplate.Shared.Infra` namespace and all the classes in it.

2022-05-18 05:54 UTC, ysmoradi approved these changes

2022-05-18 06:40 UTC, msynk approved these changes

2022-05-18 06:42 UTC, merged