Add a demo for the `Trim` on the `BitTextField` demo page (#2044)
bitfoundation/bitframework pull request #2064
Opened 2022-05-21 19:04 UTC by saeedhalab

This closes #2044

2022-05-22 06:58 UTC, msynk requested changes

2022-05-22 06:58 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/TextField/BitTextFieldDemo.razor
> +            <pre>type without trim :@TextValue1</pre>
please change the `pre` tag like this to be more clear:

```
<pre>type with trim: [@TrimTextvalue]</pre>
<pre>type without trim: [@TextValue1]</pre>
```

2022-05-22 06:58 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/TextField/BitTextFieldDemo.razor.cs
> +        private string TextValue1;
please rename this field to `NonTrimmedTextValue`

2022-05-22 06:58 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/TextField/BitTextFieldDemo.razor.cs
> +        private string TrimTextvalue;
please rename this field to `TrimmedTextValue`

2022-05-22 06:59 UTC, msynk commented
@maryamhdr & @Cyrus-Sushiant plz review

2022-05-22 09:17 UTC, msynk approved these changes

2022-05-22 13:14 UTC, maryamhdr requested changes

2022-05-22 13:14 UTC, maryamhdr commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/TextField/BitTextFieldDemo.razor.cs
> +        private readonly string example14HTMLCode = @"<div class=""example-desc"">The trim property removes whitespace from both sides of a string.</div>
Plz modify the desc:
`The trim property removes whitespaces from both sides of a string.`

2022-05-22 13:14 UTC, maryamhdr commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Components/TextField/BitTextFieldDemo.razor
> +            <div class="example-desc">The trim property removes whitespace from both sides of a string.</div>
Plz modify the desc:
`The trim property removes whitespaces from both sides of a string.`

2022-05-23 06:38 UTC, msynk approved these changes

2022-05-23 10:50 UTC, maryamhdr approved these changes

2022-05-23 12:01 UTC, merged