Added Feature/search box component
bitfoundation/bitframework pull request #237
Opened 2021-02-20 18:12 UTC by HamedMoghadasi

Implemented based on [microsoft fluentUI design system](https://developer.microsoft.com/en-us/fluentui#/controls/web/searchbox).

2021-04-05 17:46 UTC, msynk requested changes
This PR needs a merge from bitfoundation:develop branch.
Its base is old and so the code is not approved to be merged into the main repo.

2021-04-12 15:01 UTC, msynk commented
based on our conversations:
- move SearchBoxes folder into Components folder
- edit CSS class names
- correct the use of GetElementClass and GetElementStyle methods

2021-04-14 04:37 UTC, msynk reviewed
I've reviewed the latest pushed code and posted new comments. please take a look at these new comments.

2021-04-14 05:24 UTC, HamedMoghadasi commented on src/Client/Web/Bit.Client.Web.BlazorUI/wwwroot/scripts/bit.client.web.ts
>      }
At first, I used this code too, but then I changed it because the component didn't worked correctly (IDKW!).
So we must keep previous.

2021-04-14 05:31 UTC, HamedMoghadasi commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Index.razor
> +    }
we don't need it any more, I removed it.

2021-04-14 05:32 UTC, HamedMoghadasi commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/SearchBoxes/BitSearchBox.razor.cs
> +            ElementClassContainer.Add("bit-search-box-container");
merged !

2021-04-14 12:38 UTC, msynk approved these changes

2021-04-15 13:53 UTC, merged