Add Textfield This closes #239
bitfoundation/bitframework pull request #247
Opened 2021-03-11 21:03 UTC by mirza-developer

1- Implement BitTextField
2- Write and run test

2021-03-31 06:47 UTC, hamedhajiloo reviewed
.

2021-04-13 15:17 UTC, msynk commented
based on our conversation:
- undo changes on the project file
- merged with the latest version source code
- format .razor code
- change style and CSS class assignments based on the latest version of source code

2021-04-15 13:57 UTC, msynk requested changes
please resolve the comments

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Bit.Client.Web.BlazorUI.csproj
> +</Project>
please do not apply any changes to project files.
simply undo these changes.

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/_imports.razor
> +@using Microsoft.AspNetCore.Components.Web;
please undo this change.

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitTextField.razor.cs
> +    public enum TextFieldType
please move this enum into its own separate file.

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitTextField.razor
> +    {
It's also required to check if (Type == TextFieldType.Text) in order to render a textarea.

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitTextField.razor.cs
> +                if (Type == TextFieldType.Text)
This check is not required, it's just a property setter and should not be conditional.

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Index.razor
> +    }
move the @code content into the codebehind file (Index.razor.cs)

2021-04-15 13:57 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/_Imports.razor
> +@using Bit.Client.Web.BlazorUI;
undo this change.

2021-04-17 16:57 UTC, msynk requested changes

2021-04-17 16:57 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitTextField.razor.cs
> +        private bool _isMultiLine = false;
This line should be removed

2021-04-18 16:47 UTC, merged