Feature/fix styles structure
bitfoundation/bitframework pull request #271
Opened 2021-04-13 18:11 UTC by khashayar-pakkhesal

Remove all uses of !important 
Change styles folder location 
Enhance Styles

2021-04-18 18:28 UTC, msynk requested changes

2021-04-18 18:28 UTC, msynk commented on .gitignore
>  /src/Client/Web/Bit.Client.Web.BlazorUI/wwwroot/**/*.css
this line is redundant.

2021-04-18 20:29 UTC, khashayar-pakkhesal commented on .gitignore
>  /src/Client/Web/Bit.Client.Web.BlazorUI/wwwroot/**/*.css
Done

2021-04-20 08:27 UTC, msynk approved these changes

2021-04-20 08:28 UTC, merged