Add SetParametersAsync code generate #307
bitfoundation/bitframework pull request #354
Opened 2021-05-05 14:59 UTC by Cyrus-Sushiant

2021-05-05 15:26 UTC, msynk requested changes
there are warnings in the build that should be addressed before the merge.
and please do not apply changes in the source code that are not discussed in the issue (#307 here).

2021-05-05 15:51 UTC, ysmoradi requested changes

2021-05-05 15:51 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.SourceGenerators/Client/BlazorSetParametersSourceGenerator.cs
> +    public{(classSymbol.IsAbstract ? " abstract" : null)} partial class {classSymbol.Name}
It's not required!

2021-05-06 05:27 UTC, ysmoradi requested changes

2021-05-06 05:27 UTC, ysmoradi commented on src/Tooling/Bit.Tooling.SourceGenerators/Client/BlazorSetParametersSourceGenerator.cs
> +                string classSource = GeneratePartialClassToOverrideSetParameters(group.Key as INamedTypeSymbol, group.ToList());
Please use cast instead of as
We use as in rare cases in which there is uncertainty about the object's real type.

2021-05-06 08:33 UTC, msynk commented on src/Tooling/Bit.Tooling.SourceGenerators/Client/BlazorSetParametersSourceGenerator.cs
> +    public{(classSymbol.IsAbstract ? " abstract" : null)} partial class {classSymbol.Name}
+1

2021-05-06 08:38 UTC, msynk approved these changes

2021-05-06 08:51 UTC, ysmoradi approved these changes

2021-05-06 08:51 UTC, merged