Fix issue in bit button test (#400)
bitfoundation/bitframework pull request #401
Opened 2021-05-16 13:49 UTC by SomayeEbrahimi

2021-05-16 17:05 UTC, msynk requested changes

2021-05-16 17:05 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Buttons/BitButtonLinkTest.razor
> +﻿<CascadingValue Value="Visual">
This approach to resolving the Test issues is not accepted.
please consider the correct solution (resolving the ambiguity of the "string" parameter using @ character) as we talked about in our meeting.

2021-05-17 14:48 UTC, msynk requested changes

2021-05-17 14:48 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Buttons/BitButtonTest.razor
> +               Target=@Target>
Is there any reason for only the "Target" parameter's value has no double quotation mark?

2021-05-17 14:48 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Buttons/BitButtonTest.razor
> +               AriaHidden="@AriaHidden"
the "AriaHidden" parameter does not require the "@" in its value, because its type is not string

2021-05-19 15:11 UTC, merged

2021-05-19 16:16 UTC, ysmoradi commented
Thanks so much @SomayeEbrahimi 
Working on tests is really appreciated!