Add BitDropDown This close #258
bitfoundation/bitframework pull request #426
Opened 2021-05-23 09:06 UTC by mirza-developer

2021-06-05 12:00 UTC, msynk requested changes

2021-06-05 12:01 UTC, msynk commented
please resolve the conflicts too :)

2021-06-05 19:21 UTC, mirza-developer commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Component.razor
> -<hr />
I can't understand this comment
Please tell more detail

2021-06-06 03:38 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Pages/Component.razor
> -<hr />
The changes shown here are related to another component, if it is not actually changed and the diff tools showing it wrongly, ignore this comment.

2021-06-07 04:44 UTC, msynk requested changes
Please resolve the Nullable Reference Type warnings only for the files changed in this PR

2021-06-07 04:44 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Inputs/BitDropDownTest.razor
> +    }
code formatting issue

2021-06-07 04:44 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Inputs/BitInputTests.cs
>  ﻿using System.Linq;
This file should not be changed in this PR, please move the required changes into another branch and submit a new PR for a related issue.

2021-06-07 04:44 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Inputs/BitDropDownTests.cs
> +         DataRow(Visual.Fluent,true,1,true,"enabled"),
code formatting issues

2021-06-07 04:44 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitDropDown.razor.cs
> +            ClassBuilder.Register(() => string.IsNullOrWhiteSpace(FocusClass)
did you miss this one?

2021-06-07 18:27 UTC, msynk requested changes

2021-06-07 18:27 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Inputs/BitInputTests.cs
>  ﻿using System.Linq;
did you miss rolling back these changes?

2021-06-10 15:01 UTC, msynk approved these changes

2021-06-10 15:02 UTC, merged