add ArbitraryAttributes parameter (#274)
bitfoundation/bitframework pull request #438
Opened 2021-06-06 20:59 UTC by maryamhdr

2021-06-07 04:35 UTC, ysmoradi commented
Finally!
It was missing
Anyway, shall we write at least one unit test for this? for example using BitButton and arbitrary attributes?
@maryamhdr @msynk

2021-06-10 09:30 UTC, msynk commented
Unfortunately, It seems this implementation does not work!
It might be because of the difference between the definition location of the property vs the usage location of it and how the SetParametersAsync is overridden in this project.

2021-06-10 09:34 UTC, msynk requested changes
please provide some unit test for this new feature and also some demo implementations in Palygound project

2021-06-13 20:46 UTC, msynk commented
let's move writing appropriate unit tests for this feature to another issue.

2021-06-13 21:41 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Inputs/BitChoiceOption.razor.cs
>          public override Task SetParametersAsync(ParameterView parameters)
I'm with the investigation and we can safely remove this method completely

2021-06-13 21:56 UTC, msynk approved these changes

2021-06-13 21:56 UTC, merged