Feature/260 add slider component
bitfoundation/bitframework pull request #468
Opened 2021-06-12 11:27 UTC by Cyrus-Sushiant

2021-06-27 05:29 UTC, msynk commented
please consider applying our convention for branch names

2021-06-27 05:30 UTC, msynk commented
this branch has some compile errors. please resolve them ASAP

2021-07-05 14:50 UTC, msynk requested changes

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +        private string styleProgress;
please resolve the non-null warning for this property

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +        private string styleContainer;
please resolve the non-null warning for this property

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +        [Inject] public IJSRuntime JSRuntime { get; set; }
please resolve the non-null warning for this property

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +        [Parameter] public string Label { get; set; }
please resolve the non-null warning for this property

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +        [Parameter] public string ValueFormat { get; set; }
please resolve the non-null warning for this property

2021-07-05 14:50 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Sliders/BitSlider.razor.cs
> +                return val.ToString();
please resolve the null reference warning for this line

2021-07-10 16:11 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Sliders/BitSliderTests.cs
> +            return Task.CompletedTask;
Which line? 83?

2021-07-10 16:41 UTC, msynk commented
This PR has some build errors. please resolve them.

2021-07-21 15:59 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Sliders/BitSliderTests.cs
> +                Assert.AreEqual(item.GetAttribute("max"), (max.HasValue ? max.Value : com.Instance.Max).ToString());
The default value doesn't work in Bunit.

2021-07-21 15:59 UTC, Cyrus-Sushiant commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Sliders/BitSliderTests.cs
> +                Assert.AreEqual(item.GetAttribute("step"), (step.HasValue ? step.Value : com.Instance.Step).ToString());
The default value doesn't work in Bunit.

2021-08-23 19:48 UTC, msynk approved these changes

2021-08-23 19:48 UTC, merged