Add aria-label attributes to all components (#399)
bitfoundation/bitframework pull request #520
Opened 2021-06-28 11:20 UTC by FatemehNoroozi

This closes #399

2021-06-28 15:17 UTC, msynk commented
please resolve the conflicts

2021-07-01 05:16 UTC, msynk requested changes

2021-07-01 05:16 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/SearchBoxes/BitSearchBoxTests.cs
> +            return Task.CompletedTask;
please remove this redundant line

2021-07-01 05:16 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/SearchBoxes/BitSearchBoxTests.cs
> +            Assert.IsTrue(bitSearchBox.GetAttribute("aria-label").Contains(ariaLabel));
please use the "Equals" method instead of "Contains"

2021-07-01 05:16 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Toggles/BitToggleTests.cs
> +            Assert.IsTrue(bitToggle.GetAttribute("aria-label").Contains(ariaLabel));
please use the "Equals" method instead of "Contains"

2021-07-01 05:16 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Toggles/BitToggleTests.cs
> +            var bitToggle = com.Find(".bit-tgl  button");
excess space in the selector string

2021-07-01 05:16 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Toggles/BitToggleTests.cs
> +            return Task.CompletedTask;
please remove this redundant line

2021-07-01 09:28 UTC, FatemehNoroozi commented on src/Client/Web/Bit.Client.Web.BlazorUI.Tests/Pivot/BitPivotTests.cs
> +            var bitPivot = com.Find(".bit-pvt-itm");
Yes it worked, but I will check again

2021-07-04 14:18 UTC, msynk commented
please resolve the conflicts

2021-07-07 18:41 UTC, closed without merging