Add selected style and default title to BitNav Component
bitfoundation/bitframework pull request #565
Opened 2021-07-06 06:59 UTC by zoha-shobbar

this close #547

2021-07-07 18:14 UTC, msynk requested changes

2021-07-07 18:14 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Navs/BitNav.razor
> +               title=" @(navLink.Title.HasValue()?navLink.Title:navLink.Name)"
please format the added code correctly

2021-07-08 19:30 UTC, zoha-shobbar commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Navs/BitNav.razor
> +               title=" @(navLink.Title.HasValue()?navLink.Title:navLink.Name)"
done

2021-07-10 08:55 UTC, msynk requested changes

2021-07-10 08:55 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Styles/Fluent/Navs/bit-nav.fluent.scss
> +        &:hover, &:focus {
I think this is not correct.

2021-07-10 08:55 UTC, msynk commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/Navs/BitNav.razor
> -            @if (navLink.Url.HasValue())
why this line (the if statement) is removed?

2021-07-14 14:52 UTC, msynk approved these changes

2021-07-14 14:53 UTC, merged