bit file upload url issue (#698)
bitfoundation/bitframework pull request #700
Opened 2021-08-22 13:34 UTC by Md23Mh

This closes #698

2021-08-23 19:45 UTC, msynk requested changes

2021-08-23 19:45 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/Controllers/FileUploadController.cs
> +            BasePath = $"{Configuration["UploadPath"]}";
isn't `Configuration["UploadPath"]` itself a string?

2021-08-23 19:45 UTC, msynk commented on src/Client/Web/Playground/Bit.Client.Web.BlazorUI.Playground/Web/appsettings.json
> +  "UploadPath": "D:\\UploadFiles\\"
please choose a better path, for example, `C:\BitFileUploaderFiles`

2021-08-25 06:37 UTC, Md23Mh commented on src/Client/Web/Bit.Client.Web.BlazorUI/Components/FileUploads/BitFileUpload.razor.cs
> +        [Parameter] public string RemoveUrl { get; set; }
Got it.

2021-08-25 07:13 UTC, msynk approved these changes

2021-08-25 07:13 UTC, merged